// QA Test Data — 챌린지 목록 (challenge-list)
// 이 파일은 qa-tester 에이전트가 관리합니다. 수동 수정 시 주의.
window.__TEST_DATA__ = {
  "feature": "챌린지 목록",
  "screen": "challenge-list",
  "lastUpdated": "2026-06-18",
  "priority": "medium",
  "cases": [
    {
      "id": "CL-N-001",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "REGULAR 탭 — 카테고리 2열 그리드 정상 표시",
      "precondition": "REGULAR 유형 카테고리가 1개 이상 존재, 각 카테고리에 노출 조건 충족 챌린지 1개 이상",
      "action": "홈 → 'New Challenge' 탭 → 카테고리 선택 화면 진입",
      "expected": "REGULAR 탭 활성, 참여 가능 카테고리 2열 그리드 표시 (아이콘 + displayName + challengeCount)",
      "dbCheck": "CHALLENGE_CATEGORY(active=true) + CHALLENGE(challenge_type=REGULAR, 노출 조건 충족) 조회 확인"
    },
    {
      "id": "CL-N-002",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "EVENT 탭 — 챌린지 카드 목록 바로 표시 (카테고리 선택 없음)",
      "precondition": "EVENT 유형 챌린지가 1개 이상 존재",
      "action": "카테고리 선택 화면 → EVENT 탭 선택",
      "expected": "EVENT 탭 활성, 카테고리 그리드 없이 바로 챌린지 카드 목록 표시 (sortOrder ASC, updatedAt DESC), 카드에 카테고리 뱃지(아이콘+displayName) 포함, Currently Active 섹션 없음",
      "dbCheck": "CHALLENGE(challenge_type=EVENT, active=true, 노출 조건 충족) 조회 확인"
    },
    {
      "id": "CL-N-003",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "개인화 정렬 — 최근 완료 카테고리 상단 배치",
      "precondition": "사용자가 카테고리A 챌린지 COMPLETED, 카테고리B 미참여, 카테고리C 미참여 (sortOrder: C < B < A)",
      "action": "카테고리 선택 화면 진입",
      "expected": "카테고리A(최근 완료)가 최상단, 카테고리B/C는 sortOrder 순으로 표시",
      "dbCheck": "CHALLENGE_PARTICIPATION(user_id, status=COMPLETED/FAILED) 종료일 DESC 정렬 확인"
    },
    {
      "id": "CL-N-004",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Currently Active 섹션 분리 (진행 중 카테고리)",
      "precondition": "사용자가 카테고리X에서 ACTIVE 참여 중 (endsAt >= today)",
      "action": "카테고리 선택 화면 진입",
      "expected": "카테고리X가 하단 'Currently Active' 섹션에 반투명 + 🔒 + 'In Progress' 라벨로 표시, 상단 그리드에서 제외",
      "dbCheck": "CHALLENGE_PARTICIPATION(user_id, status=ACTIVE, ends_at >= today) → 해당 카테고리 active 섹션 분류"
    },
    {
      "id": "CL-N-005",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "잠금 카테고리 탭 시 안내 모달 표시",
      "precondition": "Currently Active 섹션에 잠금 카테고리 존재",
      "action": "잠금 카테고리 카드 탭",
      "expected": "안내 메시지 표시: 'You already have an active challenge in this category. Complete it first to start a new one.' + 'Go to My Challenges' 버튼 + 'Close' 버튼",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-006",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "'Go to My Challenges' 버튼 동작",
      "precondition": "잠금 카테고리 탭 → 안내 모달 표시 상태",
      "action": "'Go to My Challenges' 버튼 탭",
      "expected": "내 챌린지 화면으로 네비게이션",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-006-1",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "잠금 안내 모달 'Close' 버튼 동작",
      "precondition": "잠금 카테고리 탭 → 안내 모달 표시 상태",
      "action": "'Close' 버튼 탭",
      "expected": "모달 닫힘, 카테고리 선택 화면 유지 (네비게이션 없음)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-007",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "참여 가능 카테고리 탭 → 챌린지 목록 화면 이동",
      "precondition": "참여 가능 카테고리(available 섹션)가 표시된 상태",
      "action": "참여 가능 카테고리 카드 탭",
      "expected": "해당 카테고리의 챌린지 목록 화면으로 이동 (카테고리 아이콘 + displayName 상단 표시)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-008",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "신규 사용자 — sortOrder 기본 정렬",
      "precondition": "사용자의 챌린지 참여 이력 0건 (신규 가입)",
      "action": "카테고리 선택 화면 진입",
      "expected": "모든 카테고리가 참여 가능 상태, sortOrder ASC 정렬, Currently Active 섹션 미표시",
      "dbCheck": "CHALLENGE_PARTICIPATION(user_id) = 0건 확인"
    },
    {
      "id": "CL-N-009",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 내 챌린지 목록 — 카드 정상 표시",
      "precondition": "선택한 카테고리에 노출 조건 충족 챌린지 1개 이상",
      "action": "참여 가능 카테고리 탭 → 챌린지 목록 화면",
      "expected": "챌린지 카드 목록 표시: 제목, 설명, 뱃지 라인(난이도 + 인기도 + 리워드 비율), 메타 3칸(Duration/Frequency/Deposit), 카테고리 표시 없음",
      "dbCheck": "CHALLENGE(category_id=선택값, 노출 조건 충족) 조회 확인"
    },
    {
      "id": "CL-N-010",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 내 챌린지 목록 — 카테고리 표시 제거 확인",
      "precondition": "카테고리 내 챌린지 목록 화면 진입",
      "action": "챌린지 카드 확인",
      "expected": "카드에 카테고리명 미표시 (이미 카테고리 화면 안이므로), 상단에 카테고리 아이콘 + displayName만 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-011",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "인기도 뱃지 표시 (Popular / Legend)",
      "precondition": "totalParticipants 50~499명 챌린지, 500명 이상 챌린지 각각 존재",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "50~499명: 🔥 Popular (gradient-yellow), 500명 이상: 👑 Legend (gradient-blue), 50명 미만: 뱃지 없음",
      "dbCheck": "CHALLENGE(total_participants) 값 확인"
    },
    {
      "id": "CL-N-012",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "잔여 인원 표시 (spots left)",
      "precondition": "max_participants 설정 챌린지, ACTIVE 참여자 수가 max - 5 이하 잔여",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "해당 카드에 'N spots left' 표시 (잔여 5명 이하일 때만)",
      "dbCheck": "CHALLENGE(max_participants) - CHALLENGE_PARTICIPATION(challenge_id, status=ACTIVE) COUNT <= 5"
    },
    {
      "id": "CL-N-013",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "페이지네이션 동작 (5건 단위)",
      "precondition": "해당 카테고리에 챌린지 6개 이상 존재",
      "action": "목록 하단 Next 버튼 클릭",
      "expected": "2페이지 챌린지 표시, 현재 페이지 하이라이트, Prev 활성화, 1페이지에서 Prev 비활성",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-014",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "챌린지 카드 탭 → 상세 화면 이동",
      "precondition": "카테고리 내 챌린지 목록에 카드 표시 상태",
      "action": "챌린지 카드 탭",
      "expected": "해당 챌린지 상세 화면으로 네비게이션",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-015",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "BackButton → 카테고리 선택 화면 복귀",
      "precondition": "카테고리 내 챌린지 목록 화면",
      "action": "Telegram BackButton 탭",
      "expected": "카테고리 선택 화면으로 복귀, 이전 탭(REGULAR/EVENT) 상태 유지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-016",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "FIXED_PERIOD 챌린지 노출 조건 (시작일 7일 전~종료일)",
      "precondition": "FIXED_PERIOD 챌린지: fixed_start_date <= today+7, fixed_end_date >= today",
      "action": "해당 카테고리 챌린지 목록 확인",
      "expected": "해당 FIXED_PERIOD 챌린지가 목록에 표시됨",
      "dbCheck": "CHALLENGE(schedule_type=FIXED_PERIOD, fixed_start_date <= today+7, fixed_end_date >= today)"
    },
    {
      "id": "CL-N-017",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "RELATIVE_DAYS 챌린지 항상 노출",
      "precondition": "RELATIVE_DAYS 챌린지가 해당 카테고리에 존재",
      "action": "해당 카테고리 챌린지 목록 확인",
      "expected": "RELATIVE_DAYS 챌린지가 항상 목록에 표시됨",
      "dbCheck": "CHALLENGE(schedule_type=RELATIVE_DAYS, category_id=선택값) 조회 확인"
    },
    {
      "id": "CL-N-018",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 중복 참여 제한 — 포기 후 같은 카테고리 즉시 재참여 가능",
      "precondition": "사용자가 카테고리X 챌린지를 GIVEN_UP 처리 완료",
      "action": "카테고리 선택 화면 진입",
      "expected": "카테고리X가 available 섹션에 표시 (잠금 아님), 탭 시 챌린지 목록 이동 가능",
      "dbCheck": "CHALLENGE_PARTICIPATION(user_id, category_id=X, status=GIVEN_UP) 확인, ACTIVE 건 없음"
    },
    {
      "id": "CL-N-019",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 중복 참여 제한 — 다른 카테고리 동시 참여 가능",
      "precondition": "사용자가 카테고리A에서 ACTIVE 참여 중",
      "action": "카테고리B(다른 카테고리) 탭 → 챌린지 선택 → 참여",
      "expected": "카테고리B 챌린지 참여 성공 (카테고리A와 무관)",
      "dbCheck": "CHALLENGE_PARTICIPATION(user_id, category_id=B, status=ACTIVE) 신규 생성 확인"
    },
    {
      "id": "CL-E-001",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 없음 — 빈 상태 (REGULAR 탭)",
      "precondition": "REGULAR 유형 카테고리 0개 (또는 모든 카테고리의 challengeCount=0)",
      "action": "카테고리 선택 화면 → REGULAR 탭",
      "expected": "'No categories available' 빈 상태 메시지, Currently Active 섹션 미표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-E-002",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "EVENT 탭 — 빈 상태 (이벤트 챌린지 0개)",
      "precondition": "EVENT 유형 챌린지가 0개 (또는 모두 비활성/노출 조건 미충족)",
      "action": "카테고리 선택 화면 → EVENT 탭 선택",
      "expected": "EVENT 탭 활성, EmptyState: ⚡ 아이콘 + 'No Events Available' + 'There are no events at the moment. Check back later!' + 페이지네이션 미표시",
      "dbCheck": "CHALLENGE(challenge_type=EVENT, active=true, 노출 조건 충족) 0건 확인"
    },
    {
      "id": "CL-E-003",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 내 챌린지 없음 — 빈 상태",
      "precondition": "선택한 카테고리에 노출 조건 충족 챌린지 0건",
      "action": "해당 카테고리 탭 → 챌린지 목록 화면",
      "expected": "카테고리 아이콘 + displayName 상단 표시, 'No challenges available in this category' 메시지, 페이지네이션 미표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-E-004",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "FIXED_PERIOD 챌린지 시작일 8일 전 미노출",
      "precondition": "FIXED_PERIOD 챌린지: fixed_start_date > today+7",
      "action": "해당 카테고리 챌린지 목록 확인",
      "expected": "해당 챌린지가 목록에 표시되지 않음",
      "dbCheck": "CHALLENGE(fixed_start_date > today+7) 해당 건 미노출 확인"
    },
    {
      "id": "CL-E-005",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "FIXED_PERIOD 챌린지 종료일 경과 후 미노출",
      "precondition": "FIXED_PERIOD 챌린지: fixed_end_date < today",
      "action": "해당 카테고리 챌린지 목록 확인",
      "expected": "해당 챌린지가 목록에 표시되지 않음",
      "dbCheck": "CHALLENGE(fixed_end_date < today) 해당 건 미노출 확인"
    },
    {
      "id": "CL-E-006",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "참여 인원 마감 챌린지 'Full' 표시",
      "precondition": "max_participants 설정 챌린지, ACTIVE 참여자 수 = max_participants",
      "action": "해당 카테고리 챌린지 목록 확인",
      "expected": "해당 카드에 'Full' 뱃지 표시 또는 목록에서 제외",
      "dbCheck": "CHALLENGE_PARTICIPATION(challenge_id, status=ACTIVE) COUNT = max_participants"
    },
    {
      "id": "CL-E-007",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "같은 카테고리 ACTIVE 참여 중 신규 참여 시도 → 409 에러",
      "precondition": "사용자가 카테고리X에서 ACTIVE 참여 중 (endsAt >= today)",
      "action": "카테고리X의 다른 챌린지 상세 → 참여 시도 (API 직접 호출 또는 우회)",
      "expected": "409 에러: 'You already have an active challenge in this category'",
      "dbCheck": "CHALLENGE_PARTICIPATION 신규 생성 없음, 기존 ACTIVE 건 유지"
    },
    {
      "id": "CL-E-008",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "endsAt 지난 ACTIVE 참여는 제한 대상 제외 (정산 대기)",
      "precondition": "사용자가 카테고리X에서 ACTIVE 참여 중이나 endsAt < today (정산 대기 상태)",
      "action": "카테고리 선택 화면 진입",
      "expected": "카테고리X가 available 섹션에 표시 (잠금 아님), 신규 참여 가능",
      "dbCheck": "CHALLENGE_PARTICIPATION(user_id, category_id=X, status=ACTIVE, ends_at < today) → 제한 대상 제외"
    },
    {
      "id": "CL-E-009",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 목록 API 실패 — 에러 상태",
      "precondition": "서버 오류 또는 네트워크 단절",
      "action": "카테고리 선택 화면 진입",
      "expected": "에러 메시지 표시 + 재시도 버튼",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-E-010",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "챌린지 목록 API 실패 — 에러 상태",
      "precondition": "카테고리 선택 후 챌린지 목록 API 호출 실패",
      "action": "참여 가능 카테고리 탭",
      "expected": "에러 메시지 표시 + 재시도 버튼",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-E-011",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "challengeCount=0인 카테고리 미표시",
      "precondition": "카테고리는 active=true이나 해당 카테고리에 노출 조건 충족 챌린지 0건",
      "action": "카테고리 선택 화면 진입",
      "expected": "해당 카테고리가 그리드에 표시되지 않음 (available, active 모두 제외)",
      "dbCheck": "CHALLENGE(category_id=해당값, 노출 조건 충족) COUNT = 0 확인"
    },
    {
      "id": "CL-N-020",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "리워드 뱃지 표시 — 1~9% (Low, outline 스타일)",
      "precondition": "rewardRate=0.08 (8%) 챌린지 존재",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "해당 카드에 \"+8%\" 뱃지 표시 (outline 스타일, neutral 톤, 배경 투명)",
      "dbCheck": "CHALLENGE(reward_rate=0.08) 확인"
    },
    {
      "id": "CL-N-021",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "리워드 뱃지 표시 — 10~19% (Mid, success filled)",
      "precondition": "rewardRate=0.12 (12%) 챌린지 존재",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "해당 카드에 \"+12%\" 뱃지 표시 (초록 배경, 흰 텍스트, filled 스타일)",
      "dbCheck": "CHALLENGE(reward_rate=0.12) 확인"
    },
    {
      "id": "CL-N-022",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "리워드 뱃지 표시 — 20%+ (High, 금색 그라디언트 + 아이콘)",
      "precondition": "rewardRate=0.25 (25%) 챌린지 존재",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "해당 카드에 \"🎁 +25%\" 뱃지 표시 (금색 그라디언트 배경, 흰 텍스트, 🎁 아이콘 포함)",
      "dbCheck": "CHALLENGE(reward_rate=0.25) 확인"
    },
    {
      "id": "CL-N-023",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "리워드 뱃지 위치 — 난이도/인기도 뱃지와 같은 줄",
      "precondition": "rewardRate > 0인 챌린지 + totalParticipants >= 50 (인기도 뱃지도 표시)",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "뱃지 라인에 난이도 뱃지 → 인기도 뱃지 → 리워드 뱃지 순서로 한 줄에 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-E-012",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "리워드 뱃지 미표시 — rewardRate=0",
      "precondition": "rewardRate=0 챌린지 존재 (리워드 없는 챌린지)",
      "action": "카테고리 내 챌린지 목록 확인",
      "expected": "해당 카드에 리워드 뱃지 미표시",
      "dbCheck": "CHALLENGE(reward_rate=0) 확인"
    },
    {
      "id": "CL-N-025",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "탭 전환 — REGULAR ↔ EVENT 정상 동작",
      "precondition": "REGULAR 카테고리 1개 이상, EVENT 챌린지 1개 이상 존재",
      "action": "카테고리 선택 화면에서 REGULAR → EVENT → REGULAR 탭 전환",
      "expected": "REGULAR: 카테고리 2열 그리드, EVENT: 챌린지 카드 목록 바로 표시 (카테고리 선택 없음), 탭 상태 정확히 반영",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-026",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 공유 기능 — Share to Telegram",
      "precondition": "카테고리 내 챌린지 목록 화면 진입 (카테고리 아이콘 + displayName + 공유 아이콘 표시)",
      "action": "공유 아이콘(📤) 탭 → 바텀시트 → 'Share to Telegram' 탭",
      "expected": "바텀시트 표시 (2개 옵션), 'Share to Telegram' 선택 시 Telegram 네이티브 공유 다이얼로그 열림 (딥링크: startapp=cat_{categoryId}, 텍스트: 카테고리 displayName 포함)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-027",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "카테고리 공유 기능 — Copy Link",
      "precondition": "카테고리 내 챌린지 목록 화면 진입",
      "action": "공유 아이콘(📤) 탭 → 바텀시트 → 'Copy Link' 탭",
      "expected": "'Copy Link' 선택 시 공개 카테고리 URL(https://{도메인}/categories/{slug})이 클립보드에 복사됨 + 'Link copied!' 토스트 + 바텀시트 닫힘",
      "dbCheck": "변경 없음"
    },
    {
      "id": "CL-N-028",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "고정 리워드 뱃지 표시 (fixedRewardTon != null)",
      "precondition": "fixedRewardTon=2.5 챌린지 존재",
      "action": "카테고리 내 챌린지 목록 또는 EVENT 탭 챌린지 목록 확인",
      "expected": "해당 카드에 '🎁 +2.5 TON' 뱃지 표시 (고정 리워드 형태, 뱃지 라인에 위치)",
      "dbCheck": "CHALLENGE(fixed_reward_ton=2.5) 확인"
    },
    {
      "id": "CL-N-029",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "FREE 챌린지 표시 (minDepositTon=0, maxDepositTon=0)",
      "precondition": "minDepositTon=0, maxDepositTon=0인 챌린지 존재",
      "action": "카테고리 내 챌린지 목록 또는 EVENT 탭 챌린지 목록 확인",
      "expected": "해당 카드의 Deposit 정보 박스 위치에 'FREE' 텍스트 표시 (초록색)",
      "dbCheck": "CHALLENGE(min_deposit_ton=0, max_deposit_ton=0) 확인"
    },
    {
      "id": "CL-N-030",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "딥링크 진입 — startapp=cat_{categoryId} → 카테고리 챌린지 목록 직행",
      "precondition": "유효한 categoryId에 해당하는 카테고리 존재, 노출 조건 충족 챌린지 1개 이상",
      "action": "Telegram 딥링크로 진입: startapp=cat_3",
      "expected": "카테고리 선택 화면을 건너뛰고 해당 카테고리(id=3)의 챌린지 목록 화면으로 직행, BackButton으로 카테고리 선택 화면 복귀 가능",
      "dbCheck": "변경 없음"
    }
  ]
};
