// QA Test Data — 인증 제출 (verification-submit, verification-result)
// 이 파일은 qa-tester 에이전트가 관리합니다. 수동 수정 시 주의.
window.__TEST_DATA__ = {
  "feature": "인증 제출",
  "screen": "verification-submit",
  "lastUpdated": "2026-05-28",
  "priority": "high",
  "cases": [
    {
      "id": "VS-N-001",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "활성 참여 1개 — 사진 업로드 후 인증 제출 성공 (PENDING 응답)",
      "precondition": "ACTIVE 참여 1개, 오늘 해당 참여에 APPROVED 인증 없음, 5분 이내 PENDING 없음",
      "action": "홈 → DO YOUR MISSION → (Step 2 가이드 자동 진입) → Ready to Upload Photo → 사진 촬영/선택 → Submit for Verification",
      "expected": "Step 4 표시: 'Verification Submitted!' + 'Check Result' 버튼 + 'Back to Home' 버튼",
      "dbCheck": "VERIFICATION(participation_id=해당ID, final_result=PENDING, photo_hash=NOT NULL, photo_uploaded_at=NOT NULL, verified_date=오늘)"
    },
    {
      "id": "VS-N-002",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "활성 참여 2개 이상 — 챌린지 선택 후 인증 제출 성공",
      "precondition": "ACTIVE 참여 2개 이상, 오늘 인증 미완료 챌린지 존재",
      "action": "홈 → DO YOUR MISSION → Step 1에서 챌린지 카드 탭 → Step 2 가이드 → Ready to Upload Photo → 사진 선택 → Submit for Verification",
      "expected": "Step 1에 챌린지 목록 표시 (아이콘, 이름, Day X of Y, 진행률%), 선택 후 Step 4까지 정상 진행",
      "dbCheck": "VERIFICATION(participation_id=선택한 참여ID, final_result=PENDING)"
    },
    {
      "id": "VS-N-003",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "AI 판정 APPROVED — 인증 결과 화면에서 성공 표시",
      "precondition": "PENDING 상태 인증 존재, AI 판정 완료 (APPROVED)",
      "action": "인증 결과 화면 진입 (Check Result 탭 또는 Telegram 알림 딥링크)",
      "expected": "녹색 배경 + '✅ Perfect! Mission Complete!' + 스트릭 정보 '🔥 X Day Streak' + 'Back to Home' 버튼",
      "dbCheck": "VERIFICATION(final_result=APPROVED, ai_result=APPROVED, ai_judged_at=NOT NULL, ai_reason=NOT NULL)"
    },
    {
      "id": "VS-N-004",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "AI 판정 REJECTED — 인증 결과 화면에서 실패 표시 + 재시도/이의제기 버튼",
      "precondition": "PENDING 상태 인증 존재, AI 판정 완료 (REJECTED)",
      "action": "인증 결과 화면 진입",
      "expected": "빨간 배경 + '❌ Verification Failed' + AI 거부 사유 표시 + 'Try Again' + 'File a Dispute' + 'Back to Home' 버튼",
      "dbCheck": "VERIFICATION(final_result=REJECTED, ai_result=REJECTED, ai_reason=NOT NULL)"
    },
    {
      "id": "VS-N-005",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "REJECTED 후 같은 날 재시도 성공",
      "precondition": "오늘 REJECTED 인증 존재, 5분 이내 PENDING 없음",
      "action": "인증 결과 화면 → Try Again → 새 사진 촬영 → Submit for Verification",
      "expected": "새 인증 PENDING 생성, AI 판정 후 APPROVED 시 성공 화면 표시",
      "dbCheck": "VERIFICATION 새 레코드 INSERT(participation_id=동일, final_result=PENDING, verified_date=오늘) — 이전 REJECTED 건은 그대로 유지"
    },
    {
      "id": "VS-N-006",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "이의제기 제출 성공",
      "precondition": "REJECTED 상태 인증, 해당 인증에 이의제기 미제출 상태",
      "action": "인증 결과 화면 → File a Dispute → 사유 입력 (10~500자) → Submit Dispute",
      "expected": "'📋 Dispute Submitted' + '어드민 검토 후 알림' 안내 표시",
      "dbCheck": "VERIFICATION(dispute_requested=true, dispute_reason=입력값, dispute_requested_at=NOT NULL)"
    },
    {
      "id": "VS-N-007",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "PENDING 상태에서 폴링으로 결과 자동 전환",
      "precondition": "방금 인증 제출 완료 (PENDING 상태)",
      "action": "인증 결과 화면 진입 → 대기 (3초 간격 폴링)",
      "expected": "로딩 인디케이터 표시 → AI 판정 완료 시 자동으로 APPROVED/REJECTED 화면 전환 + 햅틱 피드백",
      "dbCheck": "변경 없음 (폴링은 조회만)"
    },
    {
      "id": "VS-N-008",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "초과 인증 — 주기 필요 횟수 초과해도 인증 가능",
      "precondition": "이번 주기 required_verifications=3, 이미 3회 APPROVED 완료",
      "action": "인증 제출 화면 진입 → 사진 업로드 → Submit for Verification",
      "expected": "정상 제출 성공 (차단 없음), PENDING 응답",
      "dbCheck": "VERIFICATION(final_result=PENDING) 새 레코드 생성 — cappedSuccessCount는 cap 이상 증가하지 않음"
    },
    {
      "id": "VS-N-009",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "인증 성공 시 Streak +1 및 DailyRecord 생성",
      "precondition": "이번 주기 required 미달성 상태, 현재 streak=2",
      "action": "인증 제출 → AI APPROVED → 주기 내 required 달성",
      "expected": "인증 결과 화면에서 '🔥 3 Day Streak' 표시",
      "dbCheck": "DAILY_RECORD(participation_id=해당ID, record_date=오늘, status=VERIFIED), CHALLENGE_PARTICIPATION(current_streak=3, capped_success_count+=1)"
    },
    {
      "id": "VS-N-010",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "포기 성공 (giveUpLimitDays 이내)",
      "precondition": "ACTIVE 참여, 참여 시작 후 giveUpLimitDays(기본 3일) 이내, deposit_ton=10",
      "action": "인증 제출 Step 3 → Give Up → 확인 모달에서 'Give Up' 탭",
      "expected": "인증 결과 화면(GIVEN_UP): '🏳️ Challenge Abandoned' + 'Penalty: -1 TON (10%)' + 'Returned: 9 TON'",
      "dbCheck": "CHALLENGE_PARTICIPATION(status=GIVEN_UP, penalty_ton=1, current_streak=0), WALLET_BALANCE(locked_deposit_ton-=10, deposit_ton+=9), TRANSACTION(type=PENALTY, amount=1)"
    },
    {
      "id": "VS-N-011",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "모든 챌린지 오늘 인증 완료 시 All Done 표시",
      "precondition": "활성 참여 2개, 모두 오늘 APPROVED 완료",
      "action": "홈 → DO YOUR MISSION",
      "expected": "Step 1에서 '🎉 All Done!' + 'You've completed all missions for today. Come back tomorrow!' 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-N-012",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "인증 제출 후 Verify Next Challenge로 다음 챌린지 인증",
      "precondition": "활성 참여 2개 이상, 방금 1개 인증 제출 완료 (Step 4)",
      "action": "Step 4 → 'Verify Next Challenge' 탭",
      "expected": "인증 제출 화면(/verify)으로 이동, 챌린지 선택 스텝 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-001",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "5분 이내 PENDING 건 존재 시 제출 차단",
      "precondition": "같은 참여에 대해 4분 전 PENDING 상태 인증 존재",
      "action": "인증 제출 → 사진 업로드 → Submit for Verification",
      "expected": "에러: 'Please wait for your previous submission to be processed' + 제출 버튼 비활성화",
      "dbCheck": "변경 없음 (새 VERIFICATION 미생성)"
    },
    {
      "id": "VS-E-002",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "중복 사진 감지 (SHA-256 해시 일치)",
      "precondition": "전날 이전 APPROVED 인증에 사용한 사진과 동일한 사진 준비",
      "action": "인증 제출 → 동일 사진 업로드 → Submit for Verification",
      "expected": "에러: 'This photo has been used before. Please take a new photo.' + Re-upload 버튼",
      "dbCheck": "변경 없음 (VERIFICATION 미생성)"
    },
    {
      "id": "VS-E-003",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "EXIF 날짜 불일치 (어제 촬영 사진)",
      "precondition": "EXIF DateTimeOriginal이 어제 날짜인 사진 준비",
      "action": "인증 제출 → 해당 사진 업로드 → Submit for Verification",
      "expected": "에러: 'Photo date does not match today. Please take a new photo.' + Re-upload 버튼",
      "dbCheck": "변경 없음 (VERIFICATION 미생성)"
    },
    {
      "id": "VS-E-004",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "EXIF 없는 사진은 날짜 검증 패스",
      "precondition": "EXIF 메타데이터 없는 사진 (스크린샷 등)",
      "action": "인증 제출 → EXIF 없는 사진 업로드 → Submit for Verification",
      "expected": "정상 제출 성공 (EXIF 검증 스킵), PENDING 응답",
      "dbCheck": "VERIFICATION(final_result=PENDING) 정상 생성"
    },
    {
      "id": "VS-E-005",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "인증 시간 외 제출 차단",
      "precondition": "챌린지 verification_start_time=09:00, end_time=22:00, 현재 시각 23:00 (사용자 타임존 기준)",
      "action": "인증 제출 화면 진입 또는 Submit 시도",
      "expected": "'Verification is only available between 09:00 - 22:00' + 제출 버튼 비활성화",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-006",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "허용되지 않은 이미지 타입 업로드",
      "precondition": "PDF 또는 텍스트 파일 준비",
      "action": "인증 제출 → 비이미지 파일 업로드 시도",
      "expected": "에러: 이미지 타입 검증 실패 메시지 표시",
      "dbCheck": "변경 없음 (VERIFICATION 미생성)"
    },
    {
      "id": "VS-E-007",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "오늘 중복 사진은 허용 (같은 날 실패 후 재시도)",
      "precondition": "오늘 REJECTED된 인증의 사진과 동일한 해시, 전날 이전 APPROVED에는 없음",
      "action": "인증 제출 → 동일 사진 업로드 → Submit for Verification",
      "expected": "정상 제출 성공 (오늘 실패 건은 중복 체크 대상 아님)",
      "dbCheck": "VERIFICATION(final_result=PENDING) 정상 생성"
    },
    {
      "id": "VS-E-008",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "5분 초과 PENDING은 무시하고 새 제출 가능",
      "precondition": "같은 참여에 6분 전 PENDING 상태 인증 존재 (AI 호출 실패로 PENDING 유지)",
      "action": "인증 제출 → 사진 업로드 → Submit for Verification",
      "expected": "정상 제출 성공 (5분 초과 PENDING은 차단 대상 아님)",
      "dbCheck": "VERIFICATION 새 레코드 생성(final_result=PENDING)"
    },
    {
      "id": "VS-E-009",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "포기 기간 초과 시 Give Up 버튼 미표시",
      "precondition": "ACTIVE 참여, 참여 시작 후 giveUpLimitDays 초과 (예: 4일 경과, limit=3일)",
      "action": "인증 제출 Step 3 진입",
      "expected": "Give Up 버튼 미표시 (아예 렌더링 안 됨)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-010",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "이의제기 중복 제출 차단",
      "precondition": "REJECTED 인증에 이미 이의제기 제출됨 (dispute_requested=true)",
      "action": "인증 결과 화면 진입",
      "expected": "'File a Dispute' 버튼 대신 'Dispute Pending' (비활성) 또는 제출 일시 텍스트 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-011",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "APPROVED 상태에서 이의제기 불가",
      "precondition": "APPROVED 상태 인증 (비정상 접근 시도)",
      "action": "API 직접 호출: POST /api/v1/verifications/{id}/dispute",
      "expected": "에러: 'Disputes can only be filed for rejected verifications.'",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-012",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "CANCELLED 상태에서 이의제기 불가",
      "precondition": "어드민이 CANCEL 처리한 인증 (final_result=CANCELLED)",
      "action": "인증 결과 화면 진입",
      "expected": "'🚫 Verification Cancelled' + 취소 사유 표시 + 이의제기 버튼 없음",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-013",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "AI 응답 파싱 실패 시 APPROVED + needsReview=true",
      "precondition": "인증 제출 완료, AI 응답이 파싱 불가능한 형태",
      "action": "인증 제출 후 결과 확인",
      "expected": "인증 결과 화면에서 APPROVED 표시 (사용자 불이익 방지)",
      "dbCheck": "VERIFICATION(final_result=APPROVED, needs_review=true, ai_result=null 또는 APPROVED)"
    },
    {
      "id": "VS-E-014",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "네트워크 오류로 업로드 실패",
      "precondition": "네트워크 불안정 상태",
      "action": "인증 제출 → 사진 선택 → 업로드 중 네트워크 끊김",
      "expected": "'Upload failed. Please check your connection and try again.' + Retry 버튼",
      "dbCheck": "변경 없음 (VERIFICATION 미생성)"
    },
    {
      "id": "VS-E-015",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "서버 오류(500) 시 재시도 가능",
      "precondition": "서버 일시 장애",
      "action": "인증 제출 → Submit for Verification → 서버 500 응답",
      "expected": "'Something went wrong. Please try again.' + Retry 버튼, 사진 미리보기 유지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-016",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "비활성(ACTIVE 아닌) 참여에 대한 인증 시도",
      "precondition": "참여 상태가 COMPLETED 또는 FAILED 또는 GIVEN_UP",
      "action": "API 직접 호출: POST /api/v1/verifications (participationId=비활성 참여)",
      "expected": "에러: NOT_ACTIVE_PARTICIPATION",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-017",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "타인의 참여에 대한 인증 시도",
      "precondition": "다른 사용자의 participationId 사용",
      "action": "API 직접 호출: POST /api/v1/verifications (participationId=타인 참여)",
      "expected": "에러: PARTICIPATION_NOT_FOUND (404)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-018",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "인증 결과 조회 시 타인의 인증 접근 차단",
      "precondition": "다른 사용자의 verificationId",
      "action": "GET /api/v1/verifications/{타인의 verificationId}",
      "expected": "에러: VERIFICATION_NOT_FOUND (404)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-019",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "타임존 정책 FIXED — 챌린지 고정 타임존 기준 시간 검증",
      "precondition": "챌린지 timezone_policy=FIXED, fixed_timezone=Asia/Seoul, 인증 시간 09:00~22:00, 서울 시각 08:00",
      "action": "인증 제출 시도",
      "expected": "인증 시간 외 에러 (사용자 로컬 시간이 아닌 챌린지 고정 타임존 기준)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-020",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "인증 시간 제한 없는 챌린지 (24시간 가능)",
      "precondition": "챌린지 verification_start_time=NULL, end_time=NULL",
      "action": "새벽 3시에 인증 제출 시도",
      "expected": "정상 제출 성공 (시간 제한 없음)",
      "dbCheck": "VERIFICATION(final_result=PENDING) 정상 생성"
    },
    {
      "id": "VS-N-013",
      "type": "normal",
      "regression": true,
      "regressionNote": "2026-05-28 공유 버튼 분리 (Share Result → Share to Telegram + Copy Link)",
      "scenario": "APPROVED 인증 결과 공유 — 최초 공유 (Share to Telegram)",
      "precondition": "APPROVED 상태 인증, shared=false, shareUrl=null",
      "action": "인증 결과 화면 (APPROVED) → '📤 Share to Telegram' 버튼 탭",
      "expected": "share API 호출 → 성공 후 Telegram 네이티브 공유 다이얼로그 열림 (shareUrl 포함)",
      "dbCheck": "VERIFICATION(shared=true, share_token=UUID NOT NULL)"
    },
    {
      "id": "VS-N-014",
      "type": "normal",
      "regression": true,
      "regressionNote": "2026-05-28 공유 버튼 분리 (Share Again → Share to Telegram, 텍스트 변경 없음)",
      "scenario": "이미 공유된 인증 — Share to Telegram (API 호출 없이 바로 동작)",
      "precondition": "APPROVED 상태 인증, shared=true, shareUrl 존재",
      "action": "인증 결과 화면 → '📤 Share to Telegram' 버튼 탭",
      "expected": "API 호출 없이 기존 shareUrl로 Telegram 네이티브 공유 다이얼로그 열림",
      "dbCheck": "변경 없음 (기존 share_token 유지)"
    },
    {
      "id": "VS-N-015",
      "type": "normal",
      "regression": true,
      "regressionNote": "2026-05-28 공유 버튼 분리 (Share Result → Share to Telegram)",
      "scenario": "챌린지 완료 화면에서 Share to Telegram 성공",
      "precondition": "인증률 100% 달성 (challengeCompleted=true), APPROVED 상태, shared=false",
      "action": "챌린지 완료 축하 화면 → '📤 Share to Telegram' 버튼 탭",
      "expected": "share API 호출 → 성공 후 Telegram 네이티브 공유 다이얼로그 열림",
      "dbCheck": "VERIFICATION(shared=true, share_token=UUID NOT NULL)"
    },
    {
      "id": "VS-N-016",
      "type": "normal",
      "regression": true,
      "regressionNote": "2026-05-28 fallback 로직 제거 → Copy Link 독립 버튼으로 변경",
      "scenario": "APPROVED 인증 결과 공유 — 최초 공유 (Copy Link)",
      "precondition": "APPROVED 상태 인증, shared=false, shareUrl=null",
      "action": "인증 결과 화면 (APPROVED) → '🔗 Copy Link' 버튼 탭",
      "expected": "share API 호출 → 성공 후 shareUrl이 클립보드에 복사됨 + 'Link copied!' 토스트 표시",
      "dbCheck": "VERIFICATION(shared=true, share_token=UUID NOT NULL)"
    },
    {
      "id": "VS-N-017",
      "type": "normal",
      "regression": true,
      "regressionNote": "2026-05-28 버튼 텍스트 변경 로직 제거 → 2개 버튼 동등 배치 확인",
      "scenario": "이미 공유된 인증 — Copy Link (API 호출 없이 바로 동작)",
      "precondition": "APPROVED 상태 인증, shared=true, shareUrl 존재",
      "action": "인증 결과 화면 → '🔗 Copy Link' 버튼 탭",
      "expected": "API 호출 없이 기존 shareUrl이 클립보드에 복사됨 + 'Link copied!' 토스트 표시",
      "dbCheck": "변경 없음 (기존 share_token 유지)"
    },
    {
      "id": "VS-N-018",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "공유 버튼 2개 동등 배치 확인 — 텍스트 항상 고정",
      "precondition": "APPROVED 상태 인증 (shared=false 또는 shared=true 무관)",
      "action": "인증 결과 화면 진입",
      "expected": "'📤 Share to Telegram' + '🔗 Copy Link' 2개 버튼이 동등 배치 (한 줄 나란히 또는 세로), shared 여부와 무관하게 버튼 텍스트 변경 없음",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-N-019",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "챌린지 완료 화면에서 Copy Link 성공",
      "precondition": "인증률 100% 달성 (challengeCompleted=true), APPROVED 상태, shared=false",
      "action": "챌린지 완료 축하 화면 → '🔗 Copy Link' 버튼 탭",
      "expected": "share API 호출 → 성공 후 shareUrl이 클립보드에 복사됨 + 'Link copied!' 토스트 표시",
      "dbCheck": "VERIFICATION(shared=true, share_token=UUID NOT NULL)"
    },
    {
      "id": "VS-E-021",
      "type": "exception",
      "regression": true,
      "regressionNote": "2026-05-28 공유 버튼 분리 (Share Result → Share to Telegram / Copy Link)",
      "scenario": "공유 API 실패 시 에러 토스트 (어느 버튼이든 동일)",
      "precondition": "APPROVED 상태 인증, shared=false, 서버 오류 또는 네트워크 불안정",
      "action": "인증 결과 화면 → '📤 Share to Telegram' 또는 '🔗 Copy Link' 탭 → API 500 응답",
      "expected": "'Failed to share. Please try again.' 에러 토스트 표시, 화면 유지",
      "dbCheck": "변경 없음 (shared=false 유지)"
    },
    {
      "id": "VS-E-022",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "REJECTED 상태에서 공유 시도 (비정상 접근)",
      "precondition": "REJECTED 상태 인증",
      "action": "API 직접 호출: PUT /api/v1/verifications/{id}/share",
      "expected": "에러: 'Only approved verifications can be shared.' (400)",
      "dbCheck": "변경 없음 (shared=false 유지)"
    },
    {
      "id": "VS-E-023",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "타인의 인증 공유 시도 (비정상 접근)",
      "precondition": "다른 사용자의 APPROVED 인증 verificationId",
      "action": "API 직접 호출: PUT /api/v1/verifications/{타인의 id}/share",
      "expected": "에러: VERIFICATION_NOT_FOUND (404)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-024",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "공유 API 멱등성 — 이미 shared=true인 인증에 재호출",
      "precondition": "APPROVED 상태 인증, shared=true, share_token 존재",
      "action": "API 직접 호출: PUT /api/v1/verifications/{id}/share",
      "expected": "기존 shareToken + shareUrl 반환 (새로 생성하지 않음, 200 응답)",
      "dbCheck": "변경 없음 (기존 share_token 유지)"
    },
    {
      "id": "VS-E-025",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "CANCELLED 상태에서 공유 시도 (비정상 접근)",
      "precondition": "어드민 CANCEL 처리된 인증 (final_result=CANCELLED)",
      "action": "API 직접 호출: PUT /api/v1/verifications/{id}/share",
      "expected": "에러: 'Only approved verifications can be shared.' (400)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "VS-E-026",
      "type": "exception",
      "regression": true,
      "regressionNote": "2026-05-28 공유 버튼 분리 (1개 → 2개 동등 배치)",
      "scenario": "APPROVED 화면에서 공유 버튼 2개 위치 확인 (UX)",
      "precondition": "APPROVED 상태 인증",
      "action": "인증 결과 화면 진입",
      "expected": "'📤 Share to Telegram' + '🔗 Copy Link' 2개 버튼이 'Back to Home' 위에 Secondary 스타일로 동등 배치",
      "dbCheck": "변경 없음"
    }
  ]
};
