// QA Test Data — 지갑 (wallet)
// 이 파일은 qa-tester 에이전트가 관리합니다. 수동 수정 시 주의.
window.__TEST_DATA__ = {
  "feature": "지갑",
  "screen": "wallet",
  "lastUpdated": "2026-05-28",
  "priority": "critical",
  "cases": [
    {
      "id": "WL-N-001",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "지갑 잔액 조회 성공 (Deposit/Locked/Reward 분리 표시)",
      "precondition": "사용자 로그인 완료, WALLET_BALANCE 레코드 존재 (depositTon=10, lockedDepositTon=5, rewardTon=3)",
      "action": "홈 화면에서 Wallet 카드 탭",
      "expected": "Deposit: 10 TON, Locked: 5 TON, Reward: 3 TON 각각 표시",
      "dbCheck": "WALLET_BALANCE(depositTon=10, lockedDepositTon=5, rewardTon=3)"
    },
    {
      "id": "WL-N-002",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "TON Connect 지갑 연결 성공",
      "precondition": "사용자 로그인 완료, ton_wallet_address=null (지갑 미연결)",
      "action": "Connect Wallet 버튼 탭 → TON Connect 플로우 → 지갑 앱에서 승인",
      "expected": "지갑 앱 아이콘 + 이름 + 주소 축약 표시, 구매/출금 버튼 활성화",
      "dbCheck": "USERS(ton_wallet_address=연결된 주소)"
    },
    {
      "id": "WL-N-003",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "TON 1 구매 성공 (수수료 10% 포함 1.1 TON 전송)",
      "precondition": "지갑 연결됨, 사용자 외부 지갑에 충분한 TON 보유",
      "action": "1 TON 패키지 선택 → 지갑 앱에서 1.1 TON 전송 승인",
      "expected": "Balance updated! +1 TON 토스트, depositTon 1 증가",
      "dbCheck": "WALLET_BALANCE(depositTon+=1), TRANSACTION(type=PURCHASE, amountTon=1.1, feeTon=0.1, netAmountTon=1, status=COMPLETED)"
    },
    {
      "id": "WL-N-004",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "TON 5 구매 성공 (수수료 포함 5.5 TON 전송)",
      "precondition": "지갑 연결됨, 사용자 외부 지갑에 충분한 TON 보유",
      "action": "5 TON 패키지 선택 → 지갑 앱에서 5.5 TON 전송 승인",
      "expected": "Balance updated! +5 TON 토스트",
      "dbCheck": "WALLET_BALANCE(depositTon+=5), TRANSACTION(type=PURCHASE, amountTon=5.5, feeTon=0.5, netAmountTon=5, status=COMPLETED)"
    },
    {
      "id": "WL-N-005",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "TON 60 구매 성공 (최대 패키지, 66 TON 전송)",
      "precondition": "지갑 연결됨, 사용자 외부 지갑에 충분한 TON 보유",
      "action": "60 TON 패키지 선택 → 지갑 앱에서 66 TON 전송 승인",
      "expected": "Balance updated! +60 TON 토스트",
      "dbCheck": "WALLET_BALANCE(depositTon+=60), TRANSACTION(type=PURCHASE, amountTon=66, feeTon=6, netAmountTon=60, status=COMPLETED)"
    },
    {
      "id": "WL-N-006",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "구매 멱등성 처리 (동일 idempotencyKey 재요청 시 기존 결과 반환)",
      "precondition": "지갑 연결됨, 이전에 동일 idempotencyKey로 구매 성공한 TRANSACTION 존재",
      "action": "동일 idempotencyKey로 구매 확인 API 재호출",
      "expected": "기존 구매 결과 그대로 반환, 잔액 중복 증가 없음",
      "dbCheck": "TRANSACTION(idempotencyKey=동일값, 1건만 존재), WALLET_BALANCE(변경 없음)"
    },
    {
      "id": "WL-N-007",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "지갑 연결 해제 성공 (진행 중 출금 없음)",
      "precondition": "지갑 연결됨, PENDING/PROCESSING 출금 요청 없음",
      "action": "Disconnect 버튼 탭 → 확인 팝업에서 Disconnect 탭",
      "expected": "지갑 정보 사라짐, Connect Wallet 버튼 표시, 구매/출금 비활성",
      "dbCheck": "USERS(ton_wallet_address=null)"
    },
    {
      "id": "WL-N-008",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "REWARD 출금 요청 성공",
      "precondition": "지갑 연결됨, rewardTon≥5, REWARD source에 PENDING/PROCESSING 없음",
      "action": "Withdraw 버튼 → REWARD 선택 → 5 TON 입력 → 확인",
      "expected": "출금 요청 완료 토스트, Pending Withdrawals 섹션에 표시",
      "dbCheck": "WITHDRAWAL_REQUEST(status=PENDING, amountTon=5, source=REWARD, walletAddress=연결된 주소), WALLET_BALANCE(rewardTon-=5)"
    },
    {
      "id": "WL-N-009",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "DEPOSIT 출금 요청 성공 (수수료 0%)",
      "precondition": "지갑 연결됨, depositTon≥10, DEPOSIT source에 PENDING/PROCESSING 없음",
      "action": "Withdraw 버튼 → DEPOSIT 선택 → 10 TON 입력 → 확인",
      "expected": "출금 요청 완료 토스트, 수수료 0 표시",
      "dbCheck": "WITHDRAWAL_REQUEST(status=PENDING, amountTon=10, feeTon=0, source=DEPOSIT), WALLET_BALANCE(depositTon-=10)"
    },
    {
      "id": "WL-N-010",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "출금 요청 취소 성공 (PENDING 상태)",
      "precondition": "PENDING 상태의 REWARD 출금 요청 존재 (amountTon=5)",
      "action": "출금 요청 화면에서 해당 요청 Cancel 버튼 탭",
      "expected": "취소 완료 토스트, 잔액 복원 확인",
      "dbCheck": "WITHDRAWAL_REQUEST(status=CANCELLED), WALLET_BALANCE(rewardTon+=5)"
    },
    {
      "id": "WL-N-011",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Pending Withdrawals 요약 카드 표시",
      "precondition": "PENDING 또는 PROCESSING 상태의 출금 요청 2건 존재 (총 8 TON)",
      "action": "지갑 화면 진입",
      "expected": "Pending Withdrawals (2) 카드 표시, 8 TON in progress",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-N-012",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "REWARD 출금 시 레벨 하락 확인",
      "precondition": "rewardTon=5 (Level 2), REWARD 출금 요청 3 TON",
      "action": "Withdraw → REWARD → 3 TON → 확인",
      "expected": "출금 요청 완료, 레벨 Level 2 → Level 1로 하락",
      "dbCheck": "WALLET_BALANCE(rewardTon=2), USER_STATS(level 변동 확인)"
    },
    {
      "id": "WL-N-013",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "출금 취소 시 레벨 복원 확인",
      "precondition": "PENDING REWARD 출금 3 TON 존재, 현재 rewardTon=2 (Level 1)",
      "action": "출금 요청 화면에서 Cancel 탭",
      "expected": "잔액 복원, 레벨 Level 1 → Level 2로 복원",
      "dbCheck": "WALLET_BALANCE(rewardTon=5), USER_STATS(level 복원 확인)"
    },
    {
      "id": "WL-E-001",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "지갑 미연결 상태에서 구매 시도",
      "precondition": "ton_wallet_address=null",
      "action": "구매 패키지 버튼 탭 시도",
      "expected": "버튼 비활성 상태, Connect Wallet 유도 메시지 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-002",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "지갑 미연결 상태에서 출금 시도",
      "precondition": "ton_wallet_address=null",
      "action": "Withdraw 버튼 탭 시도",
      "expected": "버튼 비활성 상태",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-003",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "구매 트랜잭션 검증 실패 (블록체인에서 트랜잭션 미발견)",
      "precondition": "지갑 연결됨, 전송 후 BE 검증 시 블록체인에서 매칭 트랜잭션 없음",
      "action": "5 TON 패키지 선택 → 전송 → BE 검증 대기 (최대 20초)",
      "expected": "Verification timed out 에러 토스트, 화면 유지",
      "dbCheck": "WALLET_BALANCE(변경 없음), TRANSACTION(생성 안 됨)"
    },
    {
      "id": "WL-E-004",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "구매 시 지갑 앱에서 거절/취소",
      "precondition": "지갑 연결됨",
      "action": "5 TON 패키지 선택 → 지갑 앱에서 거절",
      "expected": "Payment cancelled 에러 토스트, 화면 유지, 재시도 가능",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-005",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "REWARD 잔액 부족으로 출금 실패",
      "precondition": "지갑 연결됨, rewardTon=2",
      "action": "Withdraw → REWARD → 5 TON 입력 → 확인",
      "expected": "Insufficient balance 에러 메시지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-006",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "DEPOSIT 잔액 부족으로 출금 실패",
      "precondition": "지갑 연결됨, depositTon=3",
      "action": "Withdraw → DEPOSIT → 5 TON 입력 → 확인",
      "expected": "Insufficient balance 에러 메시지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-007",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "출금 금액 소수점 입력 시 거부 (정수만 가능)",
      "precondition": "지갑 연결됨, rewardTon≥5",
      "action": "Withdraw → REWARD → 3.5 TON 입력 → 확인",
      "expected": "Invalid withdrawal amount 에러 메시지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-008",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "동일 source에 PENDING 출금 존재 시 중복 요청 차단",
      "precondition": "지갑 연결됨, REWARD source에 PENDING 출금 요청 1건 존재, rewardTon≥5",
      "action": "Withdraw → REWARD → 5 TON 입력 → 확인",
      "expected": "Withdrawal already exists 에러 메시지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-009",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "REWARD PENDING 중에도 DEPOSIT 출금 가능 (source별 독립)",
      "precondition": "지갑 연결됨, REWARD source에 PENDING 존재, depositTon≥5, DEPOSIT source에 PENDING 없음",
      "action": "Withdraw → DEPOSIT → 5 TON 입력 → 확인",
      "expected": "출금 요청 성공",
      "dbCheck": "WITHDRAWAL_REQUEST(source=DEPOSIT, status=PENDING, amountTon=5), WALLET_BALANCE(depositTon-=5)"
    },
    {
      "id": "WL-E-010",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "PROCESSING 상태 출금 취소 시도 (불가)",
      "precondition": "PROCESSING 상태의 출금 요청 존재",
      "action": "출금 요청 화면에서 해당 요청 Cancel 시도",
      "expected": "Cancel 버튼 비활성 또는 에러 메시지 (PENDING만 취소 가능)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-011",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "Disconnect 시도 — PENDING 출금 존재 시 차단",
      "precondition": "지갑 연결됨, PENDING 출금 요청 1건 존재",
      "action": "Disconnect 버튼 탭",
      "expected": "Cannot disconnect wallet 경고 팝업",
      "dbCheck": "USERS(ton_wallet_address=변경 없음)"
    },
    {
      "id": "WL-E-012",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "Disconnect 시도 — PROCESSING 출금 존재 시 차단",
      "precondition": "지갑 연결됨, PROCESSING 출금 요청 1건 존재",
      "action": "Disconnect 버튼 탭",
      "expected": "Cannot disconnect wallet 경고 팝업",
      "dbCheck": "USERS(ton_wallet_address=변경 없음)"
    },
    {
      "id": "WL-E-013",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "잔액 0 상태에서 출금 버튼 비활성",
      "precondition": "지갑 연결됨, depositTon=0, rewardTon=0",
      "action": "Withdraw 버튼 탭",
      "expected": "Insufficient balance 토스트 또는 버튼 비활성",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-014",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "TON Connect 연결 실패 (네트워크 오류)",
      "precondition": "ton_wallet_address=null, 네트워크 불안정",
      "action": "Connect Wallet 버튼 탭 → 연결 시도",
      "expected": "Failed to connect wallet 에러 토스트, 화면 유지",
      "dbCheck": "USERS(ton_wallet_address=null, 변경 없음)"
    },
    {
      "id": "WL-E-015",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "잔액 조회 API 실패 (네트워크 오류)",
      "precondition": "사용자 로그인 완료, API 서버 응답 불가",
      "action": "지갑 화면 진입",
      "expected": "Failed to load wallet data 에러 + 재시도 버튼",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-N-014",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "REWARD 출금 수수료 계산 기준 — 차감 전 rewardTon 기준 레벨 적용 검증",
      "precondition": "rewardTon=7 (Level 3, 수수료 7%), 지갑 연결됨, REWARD source PENDING/PROCESSING 없음",
      "action": "Withdraw → REWARD → 7 TON 입력 → 확인",
      "expected": "수수료율은 차감 전 Level 3 기준 7% 적용 (차감 후 rewardTon=0 → Level 0이 되더라도 수수료는 7%), 수수료 0.49 TON, 실수령 6.51 TON",
      "dbCheck": "WITHDRAWAL_REQUEST(fee_ton=0.49, fee_rate=0.07), WALLET_BALANCE(rewardTon=0)"
    },
    {
      "id": "WL-N-015",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "구매 성공 후 홈 화면 이동 확인",
      "precondition": "지갑 연결됨, 5 TON 패키지 구매 성공",
      "action": "5 TON 패키지 선택 → 지갑 앱에서 5.5 TON 전송 승인 → 검증 완료",
      "expected": "Balance updated! +5 TON 토스트 후 홈 화면으로 자동 이동",
      "dbCheck": "WALLET_BALANCE(depositTon+=5)"
    },
    {
      "id": "WL-N-020",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 1 TON 구매 성공 (지갑 미연결 상태에서)",
      "precondition": "ton_wallet_address=null (지갑 미연결), 사용자 로그인 완료",
      "action": "1 TON 패키지 선택 → Stars 구매 확인 모달 → CONFIRM & PAY → Telegram 결제 UI에서 승인",
      "expected": "Balance updated! +1 TON 토스트, 홈 화면 이동",
      "dbCheck": "WALLET_BALANCE(depositTon+=1), TRANSACTION(type=PURCHASE, netAmountTon=1, paymentMethod=STARS, status=COMPLETED)"
    },
    {
      "id": "WL-N-021",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 5 TON 구매 성공 (지갑 연결 상태에서 Stars 선택)",
      "precondition": "지갑 연결됨, 사용자 로그인 완료",
      "action": "5 TON 패키지 선택 → 결제 수단 선택에서 '⭐ Pay with Stars' 선택 → CONFIRM & PAY → Telegram 결제 UI에서 승인",
      "expected": "Balance updated! +5 TON 토스트, 홈 화면 이동",
      "dbCheck": "WALLET_BALANCE(depositTon+=5), TRANSACTION(type=PURCHASE, netAmountTon=5, paymentMethod=STARS, status=COMPLETED)"
    },
    {
      "id": "WL-N-022",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 구매 멱등성 (동일 telegram_payment_charge_id 중복 처리)",
      "precondition": "이전에 동일 telegram_payment_charge_id로 successful_payment 처리 완료된 TRANSACTION 존재",
      "action": "Telegram이 동일 successful_payment Webhook 재전송",
      "expected": "잔액 중복 증가 없음, 기존 TRANSACTION 유지",
      "dbCheck": "TRANSACTION(idempotencyKey=telegram_payment_charge_id, 1건만 존재), WALLET_BALANCE(변경 없음)"
    },
    {
      "id": "WL-N-023",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 가격 조회 API 정상 응답 (5개 패키지 가격 반환)",
      "precondition": "APP_SETTINGS에 TON_TO_USD=1.90 설정됨",
      "action": "지갑 화면 진입 시 Stars 가격 표시 확인 (1/5/15/30/60 TON)",
      "expected": "각 패키지별 Stars 가격 표시 (예: 1 TON → 169⭐, 5 TON → 842⭐, 15 TON → 2,525⭐, 30 TON → 5,050⭐, 60 TON → 10,100⭐)",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-N-024",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "결제 수단 선택 UI 표시 (지갑 연결 시 패키지 선택 후)",
      "precondition": "지갑 연결됨",
      "action": "5 TON 패키지 버튼 탭",
      "expected": "'⭐ Pay with Stars — 842 ⭐' 옵션 + '💎 Pay with TON — 5.5 TON' 옵션 + 'Save ~15%' 뱃지 표시",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-N-025",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "지갑 미연결 시 Stars 가격 표시 + Connect Wallet CTA",
      "precondition": "ton_wallet_address=null (지갑 미연결)",
      "action": "지갑 화면 진입",
      "expected": "각 패키지 버튼에 Stars 가격 표시 (예: '5 TON — 842 ⭐'), 하단에 'Have TON? Connect wallet to save ~15%' 안내 + Connect Wallet 버튼",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-N-026",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "pre_checkout_query 정상 응답 (OK)",
      "precondition": "사용자가 Stars 결제 진행 중, Telegram이 pre_checkout_query Webhook 전송",
      "action": "BE가 pre_checkout_query 수신 → payload에서 packageTon 추출 → 유효성 검증",
      "expected": "answerPreCheckoutQuery(ok: true) 응답, 결제 진행 허용",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-N-027",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "successful_payment 정상 처리 (depositTon 증가)",
      "precondition": "pre_checkout_query OK 후 사용자 결제 완료, Telegram이 successful_payment 메시지 전송",
      "action": "BE가 successful_payment Webhook 수신 → idempotency 체크 → depositTon 증가",
      "expected": "depositTon 증가, Transaction 기록 생성",
      "dbCheck": "WALLET_BALANCE(depositTon+=패키지금액), TRANSACTION(type=PURCHASE, paymentMethod=STARS, idempotencyKey=telegram_payment_charge_id, status=COMPLETED)"
    },
    {
      "id": "WL-N-028",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 구매 Transaction 기록 확인 (paymentMethod=STARS, feeTon=0)",
      "precondition": "Stars 5 TON 구매 성공 완료",
      "action": "거래 내역에서 해당 Transaction 확인",
      "expected": "type=PURCHASE, netAmountTon=5, feeTon=0, paymentMethod=STARS, status=COMPLETED",
      "dbCheck": "TRANSACTION(type=PURCHASE, netAmountTon=5, feeTon=0, paymentMethod=STARS)"
    },
    {
      "id": "WL-N-029",
      "type": "normal",
      "regression": false,
      "regressionNote": "",
      "scenario": "TON Connect 구매 Transaction 기록 확인 (paymentMethod=TON_CONNECT, feeTon>0)",
      "precondition": "TON Connect 5 TON 구매 성공 완료",
      "action": "거래 내역에서 해당 Transaction 확인",
      "expected": "type=PURCHASE, amountTon=5.5, feeTon=0.5, netAmountTon=5, paymentMethod=TON_CONNECT, status=COMPLETED",
      "dbCheck": "TRANSACTION(type=PURCHASE, amountTon=5.5, feeTon=0.5, netAmountTon=5, paymentMethod=TON_CONNECT)"
    },
    {
      "id": "WL-E-020",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 결제 사용자 취소 (openInvoice cancelled)",
      "precondition": "Stars 구매 확인 모달에서 CONFIRM & PAY 탭 후 Telegram 결제 UI 표시됨",
      "action": "Telegram 결제 UI에서 취소/닫기",
      "expected": "'Payment was cancelled.' 에러 토스트, 지갑 화면 유지, 재시도 가능",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-021",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 결제 실패 (openInvoice failed)",
      "precondition": "Stars 구매 확인 모달에서 CONFIRM & PAY 탭 후 Telegram 결제 진행",
      "action": "Telegram 결제 처리 중 실패 발생 (카드 거절 등)",
      "expected": "'Payment failed. Please try again.' 에러 토스트, 지갑 화면 유지, 재시도 가능",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-022",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars invoice API 실패 (네트워크 오류)",
      "precondition": "사용자가 패키지 선택 후 Stars 결제 시도, BE API 서버 응답 불가",
      "action": "패키지 선택 → Stars 결제 → CONFIRM & PAY 탭",
      "expected": "'Failed to create payment. Please try again.' 에러 토스트, 화면 유지",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-023",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "잘못된 패키지 금액 (2 TON 등 유효하지 않은 값)",
      "precondition": "API 직접 호출로 packageTon=2 전송 (FE에서는 발생 불가)",
      "action": "POST /api/v1/wallet/stars/invoice { packageTon: 2 }",
      "expected": "400 Bad Request 에러 응답",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-024",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "Stars 결제 후 잔액 polling 5초 초과 (성공 간주)",
      "precondition": "openInvoice 콜백 'paid' 수신, Webhook 처리 지연으로 잔액 미반영",
      "action": "FE가 500ms 간격으로 잔액 API polling → 5초 초과",
      "expected": "성공 토스트 표시 + 홈 화면 이동 (Webhook 처리 지연이지 실패 아님)",
      "dbCheck": "WALLET_BALANCE(depositTon 증가 예정 — Webhook 처리 후 반영)"
    },
    {
      "id": "WL-E-025",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "pre_checkout_query 잘못된 payload (거부)",
      "precondition": "Telegram이 pre_checkout_query 전송, payload에 유효하지 않은 packageTon 포함",
      "action": "BE가 pre_checkout_query 수신 → payload 검증 실패",
      "expected": "answerPreCheckoutQuery(ok: false, error_message) 응답, 결제 거부",
      "dbCheck": "변경 없음"
    },
    {
      "id": "WL-E-026",
      "type": "exception",
      "regression": false,
      "regressionNote": "",
      "scenario": "successful_payment 중복 처리 (멱등성 — 잔액 미변경)",
      "precondition": "동일 telegram_payment_charge_id로 이미 처리 완료된 TRANSACTION 존재",
      "action": "Telegram이 동일 successful_payment Webhook 재전송",
      "expected": "중복 감지, 잔액 변경 없음, 에러 없이 정상 응답",
      "dbCheck": "TRANSACTION(1건만 존재), WALLET_BALANCE(변경 없음)"
    }
  ]
};
